### ISSUE TITLE
list-keys broken

### ISSUE THREAD

**Issue by JerryGreen** [fauna/fauna-shell#68] opened 2020-11-05 17:04 UTC
```bash
$ fauna list-keys 
listing keys
Error: Cannot read property 'id' of undefined
```

**Comment by fireridlle** [comment] 2021-04-29 08:34
Hello @JerryGreen. Which version of shell do you use?

**Comment by JerryGreen** [comment] 2021-04-29 15:44
I’m not sure which version it was, it was many months ago

I’m sure though it was the most modest version available at time of creating the issue

**Comment by JerryGreen** [comment] 2021-04-29 15:46
Oh, and you mean version of fauna-shell, or you mean shell in overall? I’m pretty sure I used macOS shell version that is installed by default

**Comment by fireridlle** [comment] 2021-04-29 17:02
version of fauna-shell
```
fauna --version
```

do you still face this issue? unable to reproduce it

**Comment by JerryGreen** [comment] 2021-05-24 12:19
I used the latest fauna version at the time of creation the issue which is a near half a year ago. I almost sure it was macOS though it might have been Windows 10. I don't use this tool anymore so can't re-check, sorry

Someone's left thumb-up for the issue, so it seems I'm not the only one facing it, but it might have been fixed indeed... Or not

**Comment by fireridlle** [comment] 2021-05-24 12:27
Thank you for your reply. I'm going to close this issue as we weren't able to reproduce with the latest version

**Closed by fireridlle** 2021-05-24 12:27 UTC
